spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: synchsmtp@sandbox46f1ced43a5d4e548b7e5b6665a69a6b.mailgun.org
    password: ${MAILGUN_PASSWORD_DEV}

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

synch:
  email:
    url: "http://localhost:8091"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8091"

logging:
  level:
    com.rvcoding.synch: DEBUG