spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.eu.mailgun.org
    username: support@mail.rvcoding.com
    password: ${MAILGUN_PASSWORD_PROD}

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

synch:
  email:
    url: "https://synch.rvcoding.com"
  rate-limit:
    ip:
      apply-limit: false  # TODO: Update to true once is ready for production.
  web-socket:
    allowed-origin: "https://synch.rvcoding.com"